
// This file was auto-generated by ML.NET Model Builder. 

using SentimentModel_ConsoleApp;

// Create single instance of sample data from first line of dataset for model input

// Get user input

Console.WriteLine("Enter some text and I'll tell you if it's positive or negative sentiment.");
Console.Write("Enter text: ");
string input = Console.ReadLine();

SentimentModel.ModelInput sampleData = new SentimentModel.ModelInput()
{
    Col0 = input!,
};

// Make a single prediction on the sample data and print results
var predictionResult = SentimentModel.Predict(sampleData);
bool isPositive = predictionResult.PredictedLabel > 0.5;

if (isPositive)
{
    Console.BackgroundColor = ConsoleColor.DarkGreen;
    Console.Clear();
    Console.ForegroundColor = ConsoleColor.White;
    Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");
    Console.WriteLine("Good to hear that!");
} else
{
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Clear();
    Console.ForegroundColor = ConsoleColor.White;
    Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");
    Console.WriteLine("Sorry to hear that!");
}


Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

